# Generated by Django 5.2.1 on 2025-05-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="customer",
        ),
    ]
