# Generated by Django 5.2.1 on 2025-05-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customers", "0002_alter_customer_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="Clientes",
        ),
    ]
