# Generated by Django 5.2.1 on 2025-05-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Park", "0001_initial"),
        ("Vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hórario de Entrada"
                    ),
                ),
                (
                    "exit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Horário de Saída"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parking_records",
                        to="Vehicle.vehicle",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga",
                "verbose_name_plural": "Vagas",
            },
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spot_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Número do Vaga"
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="Está Ocupado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Vaga de Estacionamento",
                "verbose_name_plural": "Vagas de Estacionamento",
                "db_table": "Vaga de Estacionamento",
            },
        ),
        migrations.DeleteModel(
            name="VehicleType",
        ),
        migrations.AddField(
            model_name="parkingrecord",
            name="parking_spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parking_records",
                to="Park.parkingspot",
                verbose_name="Vaga",
            ),
        ),
    ]
