# Generated by Django 5.2.1 on 2025-05-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Park", "0002_parkingrecord_parkingspot_delete_vehicletype_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="parkingrecord",
            table="Registros de Estacionamento",
        ),
    ]
